--Do not manageable

CREATE TABLE DISEASE(
	ID INT PRIMARY KEY,
	DISEASE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE RISK(
	ID INT PRIMARY KEY,
	RISK_NAME VARCHAR(50) NOT NULL,
	DISEASE_ID INT NOT NULL
);

CREATE TABLE RISK_LEVEL(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LOW_VALUE NUMBER(4, 1) NOT NULL,
	HIGH_VALUE NUMBER(4, 1) NOT NULL,
	RISK_ID INT NOT NULL
);

CREATE TABLE PATIENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	AGE INT NOT NULL,
	DOCUMENT INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE PATIENT_RISK(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DISEASE_ID INT NOT NULL,
	PATIENT_ID INT NOT NULL,
	RISK_ID INT,
	SUGAR_PERCENT NUMBER(4, 1) NOT NULL,
	FAT_PERCENT NUMBER(4, 1) NOT NULL,
	OXYGEN_PERCENT NUMBER(4, 1) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);

INSERT INTO DISEASE (ID, DISEASE_NAME) VALUES (1, 'INFECTUS DISEASE');

INSERT INTO RISK (ID, RISK_NAME, DISEASE_ID) VALUES (1, 'HIGH', 1);
INSERT INTO RISK (ID, RISK_NAME, DISEASE_ID) VALUES (2, 'MIDDLE', 1);
INSERT INTO RISK (ID, RISK_NAME, DISEASE_ID) VALUES (3, 'LOW', 1);

INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (1, 'SUGAR', 70.0, 100.0, 1);
INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (2, 'FAT', 88.5, 100.0, 1);
INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (3, 'OXYGEN', 0, 60.0, 1);

INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (4, 'SUGAR', 50.0, 70.0, 2);
INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (5, 'FAT', 62.2, 88.5, 2);
INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (6, 'OXYGEN', 60.0, 70.0, 2);

INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (7, 'SUGAR', 0, 50.0, 3);
INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (8, 'FAT', 0, 62.2, 3);
INSERT INTO RISK_LEVEL (ID, NAME, LOW_VALUE, HIGH_VALUE, RISK_ID) VALUES (9, 'OXYGEN', 70.0, 100.0, 3);

INSERT INTO PATIENT (ID, AGE, DOCUMENT, NAME, LAST_NAME, EMAIL) VALUES (1, 43, 4512178, 'Luis Eduardo', 'Garzon', 'legr@gmail.com');
INSERT INTO PATIENT (ID, AGE, DOCUMENT, NAME, LAST_NAME, EMAIL) VALUES (2, 40, 5478912, 'Erica', 'Rey', 'erey@gmail.com');
INSERT INTO PATIENT (ID, AGE, DOCUMENT, NAME, LAST_NAME, EMAIL) VALUES (3, 27, 7898745, 'Adriana', 'Olivos', 'aolivos@gmail.com');