CREATE TABLE RISKS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	RISK_NAME VARCHAR(50) NOT NULL
);

INSERT INTO RISKS(ID, RISK_NAME) VALUES (1, 'ALTO');
INSERT INTO RISKS(ID, RISK_NAME) VALUES (2, 'MEDIO');
INSERT INTO RISKS(ID, RISK_NAME) VALUES (3, 'BAJO');